// @generated by rustio 0.14.0 from .rustio/draft.toml
// SPDX-SchemaHash: sha256:031276e4839b09327dd4fbe8dbe9c4131c47dc68c08bd98709c8fa5a256134c5
// SPDX-EmitterVersion: rio-canon-1
// To change, edit draft.toml and run `rustio commit`. Manual
// edits will be overwritten.

use rustio_admin::Admin;

use super::models::diagnostic_code::DiagnosticCode;
use super::models::vehicle::Vehicle;
use super::models::scan_session::ScanSession;
use super::models::detected_fault::DetectedFault;

/// Generator-owned admin builder. `main.rs` calls this to
/// obtain an `Admin` with every model from `draft.toml`
/// registered. The developer chains further configuration
/// (`.app_name(...)`, `.public_url(...)`, etc.) after this.
pub fn build_admin() -> Admin {
    Admin::new()
        .model::<DiagnosticCode>()
        .model::<Vehicle>()
        .model::<ScanSession>()
        .model::<DetectedFault>()
}
