-- @generated by rustio 0.14.1 from .rustio/draft.toml
-- SPDX-SchemaHash: sha256:9cd3ded3059c7af1faa5c2db1d1d36df689cb0d99742cf1df3b75d381f163450
-- SPDX-EmitterVersion: rio-canon-1
-- To change, edit draft.toml and run `rustio commit`. Manual
-- edits will be overwritten.

-- Rollback hint (free-form, not parsed — DESIGN_BUILDER.md §7.5):
--   To roll back, DROP TABLE every table below in reverse order.
--   Verify FK constraints first if any have been added by hand.

CREATE TABLE diagnostic_codes (
    id                    BIGSERIAL    PRIMARY KEY,
    code                  TEXT        NOT NULL UNIQUE,
    short_title           TEXT        NOT NULL,
    detailed_description  TEXT        NOT NULL,
    system_category       TEXT        NOT NULL,
    code_type             TEXT        NOT NULL,
    severity_level        TEXT        NOT NULL,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE vehicles (
    id                      BIGSERIAL    PRIMARY KEY,
    vin                     TEXT        NOT NULL UNIQUE,
    make_name               TEXT        NOT NULL,
    model_name              TEXT        NOT NULL,
    model_year              BIGINT      NOT NULL,
    engine_displacement_cc  BIGINT      NOT NULL,
    fuel_type               TEXT        NOT NULL,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE scan_sessions (
    id                       BIGSERIAL    PRIMARY KEY,
    session_reference        TEXT        NOT NULL UNIQUE,
    vehicle_vin              TEXT        NOT NULL,
    mileage_km               BIGINT      NOT NULL,
    performed_by_technician  TEXT        NOT NULL,
    session_notes            TEXT        NOT NULL,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE detected_faults (
    id                  BIGSERIAL    PRIMARY KEY,
    fault_reference     TEXT        NOT NULL UNIQUE,
    session_reference   TEXT        NOT NULL,
    diagnostic_code     TEXT        NOT NULL,
    is_resolved         BOOLEAN     NOT NULL,
    resolution_summary  TEXT        NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
