// @generated by rustio 0.14.1 from .rustio/draft.toml
// SPDX-SchemaHash: sha256:8f47d47bca6b44fd4ebaa1994620d7ce84bf61264b2277498e0d3f2ab44db0ed
// SPDX-EmitterVersion: rio-canon-1
// To change, edit draft.toml and run `rustio commit`. Manual
// edits will be overwritten.

use chrono::{DateTime, Utc};
use rustio_admin::{Model, ModelAdmin, Result, Row, RustioAdmin, Value};

#[derive(Debug, Clone, RustioAdmin)]
pub struct DetectedFault {
    pub id: i64,
    pub fault_reference: String,
    pub session_reference: String,
    pub diagnostic_code: String,
    pub is_resolved: bool,
    pub resolution_summary: String,
    pub created_at: DateTime<Utc>,
}

impl Model for DetectedFault {
    const TABLE: &'static str = "detected_faults";
    const COLUMNS: &'static [&'static str] = &["id", "fault_reference", "session_reference", "diagnostic_code", "is_resolved", "resolution_summary", "created_at"];
    const INSERT_COLUMNS: &'static [&'static str] = &["fault_reference", "session_reference", "diagnostic_code", "is_resolved", "resolution_summary", "created_at"];

    fn id(&self) -> i64 {
        self.id
    }

    fn from_row(row: Row<'_>) -> Result<Self> {
        Ok(Self {
            id: row.get_i64("id")?,
            fault_reference: row.get_string("fault_reference")?,
            session_reference: row.get_string("session_reference")?,
            diagnostic_code: row.get_string("diagnostic_code")?,
            is_resolved: row.get_bool("is_resolved")?,
            resolution_summary: row.get_string("resolution_summary")?,
            created_at: row.get_datetime("created_at")?,
        })
    }

    fn insert_values(&self) -> Vec<Value> {
        vec![
            Value::from(self.fault_reference.clone()),
            Value::from(self.session_reference.clone()),
            Value::from(self.diagnostic_code.clone()),
            Value::from(self.is_resolved),
            Value::from(self.resolution_summary.clone()),
            Value::from(self.created_at),
        ]
    }
}

impl ModelAdmin for DetectedFault {
    fn list_display() -> &'static [&'static str] {
        &["fault_reference", "session_reference", "diagnostic_code", "is_resolved", "created_at"]
    }
    fn list_filter() -> &'static [&'static str] {
        &["is_resolved"]
    }
    fn search_fields() -> &'static [&'static str] {
        &["fault_reference", "diagnostic_code", "session_reference"]
    }
    fn ordering() -> &'static [&'static str] {
        &["-created_at"]
    }
}
