// @generated by rustio 0.14.1 from .rustio/draft.toml
// SPDX-SchemaHash: sha256:17c975e8294abf327be52e558c21eec6332da225c2711bc6a6341a1b0aece708
// SPDX-EmitterVersion: rio-canon-1
// To change, edit draft.toml and run `rustio commit`. Manual
// edits will be overwritten.

use chrono::{DateTime, Utc};
use rustio_admin::{Model, ModelAdmin, Result, Row, RustioAdmin, Value};

#[derive(Debug, Clone, RustioAdmin)]
pub struct DiagnosticCode {
    pub id: i64,
    pub code: String,
    pub short_title: String,
    pub detailed_description: String,
    pub system_category: String,
    pub code_type: String,
    pub severity_level: String,
    pub created_at: DateTime<Utc>,
}

impl Model for DiagnosticCode {
    const TABLE: &'static str = "diagnostic_codes";
    const COLUMNS: &'static [&'static str] = &["id", "code", "short_title", "detailed_description", "system_category", "code_type", "severity_level", "created_at"];
    const INSERT_COLUMNS: &'static [&'static str] = &["code", "short_title", "detailed_description", "system_category", "code_type", "severity_level", "created_at"];

    fn id(&self) -> i64 {
        self.id
    }

    fn from_row(row: Row<'_>) -> Result<Self> {
        Ok(Self {
            id: row.get_i64("id")?,
            code: row.get_string("code")?,
            short_title: row.get_string("short_title")?,
            detailed_description: row.get_string("detailed_description")?,
            system_category: row.get_string("system_category")?,
            code_type: row.get_string("code_type")?,
            severity_level: row.get_string("severity_level")?,
            created_at: row.get_datetime("created_at")?,
        })
    }

    fn insert_values(&self) -> Vec<Value> {
        vec![
            Value::from(self.code.clone()),
            Value::from(self.short_title.clone()),
            Value::from(self.detailed_description.clone()),
            Value::from(self.system_category.clone()),
            Value::from(self.code_type.clone()),
            Value::from(self.severity_level.clone()),
            Value::from(self.created_at),
        ]
    }
}

impl ModelAdmin for DiagnosticCode {}
