// @generated by rustio 0.14.0 from .rustio/draft.toml
// SPDX-SchemaHash: sha256:7106fda8656f2e72a7997f9d18e884b3071567e940d65e6cd5f992eb56eae562
// SPDX-EmitterVersion: rio-canon-1
// To change, edit draft.toml and run `rustio commit`. Manual
// edits will be overwritten.

pub mod diagnostic_code;
pub mod vehicle;
pub mod scan_session;
pub mod detected_fault;
