// @generated by rustio 0.14.1 from .rustio/draft.toml
// SPDX-SchemaHash: sha256:bc00d62778e715d588f8c66c38eed9e811e4b2cc5c3994e4f04035b16ad8156c
// SPDX-EmitterVersion: rio-canon-1
// To change, edit draft.toml and run `rustio commit`. Manual
// edits will be overwritten.

use chrono::{DateTime, Utc};
use rustio_admin::{Model, ModelAdmin, Result, Row, RustioAdmin, Value};

#[derive(Debug, Clone, RustioAdmin)]
pub struct ScanSession {
    pub id: i64,
    pub session_reference: String,
    pub vehicle_vin: String,
    pub mileage_km: i64,
    pub performed_by_technician: String,
    pub session_notes: String,
    pub created_at: DateTime<Utc>,
}

impl Model for ScanSession {
    const TABLE: &'static str = "scan_sessions";
    const COLUMNS: &'static [&'static str] = &["id", "session_reference", "vehicle_vin", "mileage_km", "performed_by_technician", "session_notes", "created_at"];
    const INSERT_COLUMNS: &'static [&'static str] = &["session_reference", "vehicle_vin", "mileage_km", "performed_by_technician", "session_notes", "created_at"];

    fn id(&self) -> i64 {
        self.id
    }

    fn from_row(row: Row<'_>) -> Result<Self> {
        Ok(Self {
            id: row.get_i64("id")?,
            session_reference: row.get_string("session_reference")?,
            vehicle_vin: row.get_string("vehicle_vin")?,
            mileage_km: row.get_i64("mileage_km")?,
            performed_by_technician: row.get_string("performed_by_technician")?,
            session_notes: row.get_string("session_notes")?,
            created_at: row.get_datetime("created_at")?,
        })
    }

    fn insert_values(&self) -> Vec<Value> {
        vec![
            Value::from(self.session_reference.clone()),
            Value::from(self.vehicle_vin.clone()),
            Value::from(self.mileage_km),
            Value::from(self.performed_by_technician.clone()),
            Value::from(self.session_notes.clone()),
            Value::from(self.created_at),
        ]
    }
}

impl ModelAdmin for ScanSession {}
