// @generated by rustio 0.14.0 from .rustio/draft.toml
// SPDX-SchemaHash: sha256:07917779f915b391cdfb54e82d744bdbcbe96284bb7c5288801f76204dee23f4
// SPDX-EmitterVersion: rio-canon-1
// To change, edit draft.toml and run `rustio commit`. Manual
// edits will be overwritten.

use chrono::{DateTime, Utc};
use rustio_admin::{Model, ModelAdmin, Result, Row, RustioAdmin, Value};

#[derive(Debug, Clone, RustioAdmin)]
pub struct Vehicle {
    pub id: i64,
    pub vin: String,
    pub make_name: String,
    pub model_name: String,
    pub model_year: i64,
    pub engine_displacement_cc: i64,
    pub fuel_type: String,
    pub created_at: DateTime<Utc>,
}

impl Model for Vehicle {
    const TABLE: &'static str = "vehicles";
    const COLUMNS: &'static [&'static str] = &["id", "vin", "make_name", "model_name", "model_year", "engine_displacement_cc", "fuel_type", "created_at"];
    const INSERT_COLUMNS: &'static [&'static str] = &["vin", "make_name", "model_name", "model_year", "engine_displacement_cc", "fuel_type", "created_at"];

    fn id(&self) -> i64 {
        self.id
    }

    fn from_row(row: Row<'_>) -> Result<Self> {
        Ok(Self {
            id: row.get_i64("id")?,
            vin: row.get_string("vin")?,
            make_name: row.get_string("make_name")?,
            model_name: row.get_string("model_name")?,
            model_year: row.get_i64("model_year")?,
            engine_displacement_cc: row.get_i64("engine_displacement_cc")?,
            fuel_type: row.get_string("fuel_type")?,
            created_at: row.get_datetime("created_at")?,
        })
    }

    fn insert_values(&self) -> Vec<Value> {
        vec![
            Value::from(self.vin.clone()),
            Value::from(self.make_name.clone()),
            Value::from(self.model_name.clone()),
            Value::from(self.model_year),
            Value::from(self.engine_displacement_cc),
            Value::from(self.fuel_type.clone()),
            Value::from(self.created_at),
        ]
    }
}

impl ModelAdmin for Vehicle {}
